/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.1 and the Signal Processing Toolbox 7.3.
 * Generated on: 20-Oct-2017 18:41:05
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 31
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\ALEX\TOOL\Matlab\extern\include\tmwtypes.h 
 */
const int BL = 31;
const real64_T coffie[31] = {
  -0.001700396903674,1.758030058129e-18, 0.002937331570891,-3.276871614433e-18,
  -0.006730091366404,6.051933223714e-18,  0.01409388790399,-9.603381523083e-18,
   -0.02678503582005,1.331713883769e-17,  0.04909896059358,-1.65510627894e-17,
    -0.0969383327763, 1.87459785477e-17,   0.3156195633245,    0.500808226947,
     0.3156195633245, 1.87459785477e-17,  -0.0969383327763,-1.65510627894e-17,
    0.04909896059358,1.331713883769e-17, -0.02678503582005,-9.603381523083e-18,
    0.01409388790399,6.051933223714e-18,-0.006730091366404,-3.276871614433e-18,
   0.002937331570891,1.758030058129e-18,-0.001700396903674
};
